### ISSUE TITLE
get data from selected autocomplete MapboxGeocoder

### ISSUE THREAD

**Issue by east87** [studiometa/vue-mapbox-gl#22]
```
<template>
  <mapbox-geocoder :access-token="accesstoken"
   @mb-results="onComplete" 
   />
</template>

<script>
//import mapboxgl from 'mapbox-gl';
import { MapboxGeocoder } from '@studiometa/vue-mapbox-gl';
import "@mapbox/mapbox-gl-geocoder/dist/mapbox-gl-geocoder.css";
export default {
  name: "geocoder",
  components: {
  //  mapboxgl,
 MapboxGeocoder
  },

  data() {
    return {
       types: "country,region,place,postcode,locality,neighborhood,address,poi", 
      accesstoken: "xxx.xxx.xxx",
      
    };
  },
  methods: {
    onComplete(response) {
      console.log(response)
    },
  },
};
</script>
```

**Comment by perruche** [comment]
Hello,

I'm not quite sure what you are trying to achieve, since your issue does not contain a lot of informations. 
I'm guessing you are trying to filter the results by types. You can achieve that using the [types](https://vue-mapbox-gl.meta.fr/components/MapboxGeocoder.html#types) prop

```
<mapbox-geocoder :access-token="accesstoken"
   @mb-results="onComplete" 
   :types="types" />
```

---

Sidenote @titouanmathis our API is not longer the same as the latest version of mapbox-gl-geocoder, [see](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md). Should update the available props ?

**Comment by east87** [comment]
I'm sorry,  i have to read your documentation. your module is so powerful bwt, thank you. 
`<template>
  <MapboxGeocoder 
  :access-token="accesstoken"
  :types="types"
  :limit="limit"
  :zoom="15"
  externalGeocoder='GeoJSON'
  :reverseGeocode="reverseGeocode"
   placeholder="search address"
   @mb-result="onComplete" 
  
   />
</template>

<script>

import { MapboxGeocoder } from '@studiometa/vue-mapbox-gl';
import "@mapbox/mapbox-gl-geocoder/dist/mapbox-gl-geocoder.css";
export default {
  name: "geocoder",
  components: {
 MapboxGeocoder
  },

  data() {
    return {
      types: "country,region,place,postcode,locality,neighborhood,address,poi", 
      accesstoken: "pk.eyJ1IjoiZxxxxxxxxxxxx",
       reverseGeocode:true,
      limit:15
      
    };
  },
  methods: {
    onComplete(result) {
      var respons= Object.keys(result).map(key => result[key]);
      console.log(respons)
      console.log(respons[0].center)
    },
  },
 
};
</script>
`

**Comment by perruche** [comment]
Glad to help !

I'm closing this issue as i think it is resolved
