### ISSUE TITLE
How to trigger geolocation on map load? 

### ISSUE THREAD

**Issue by tmlmt** [studiometa/vue-mapbox-gl#77]
How can we get access to the GeolocateControl instance so that we can use the `trigger()` function?

**Comment by titouanmathis** [comment]
The `MapboxGeolocateControl` component exposes a `control` key that you can access with a template ref (see [doc](https://vuejs.org/api/options-state.html#expose)).

Something like the following should work:

```vue
<script setup>
  import { ref, watch } from 'vue';
 
  const geolocate = ref();

  watch(geolocate, (geolocateControl) => {
    if (geolocateControl) {
      geolocateControl.control.trigger();
    }
  });
</script>

<template>
  <mapbox-map>
    <mapbox-geolocate-control ref="geolocate" />
  </mapbox-map>
</template>
```

**Comment by tmlmt** [comment]
Thanks for pointing this expose out. Unfortunately, this doesn't work. It says `Geolocate control triggered before added to a map`

In fact, the following happens: 

Log:
```
Uncaught TypeError: geolocate.value is undefined // from @mb-load (i.e. map.on('load'))
Geolocate control triggered before added to a map // that's the first doTrigger() from the watcher
// The doTrigger() after the timeout finally executes trigger() correctly
```

Code: 
```
<script setup>
  import { ref, watch } from 'vue';
 
  const geolocate = ref();

  const doTrigger = () => {
    geolocate.value.control.trigger();
  };

  watch(geolocate, (geolocateControl) => {
    if (geolocateControl) {
      doTrigger();
      setTimeout(doTrigger, 1500)
      geolocateControl.control.trigger();
    }
  });
</script>

<template>
  <mapbox-map @mb-load="doTrigger">
    <mapbox-geolocate-control ref="geolocate" />
  </mapbox-map>
</template>
```
This tends to indicate that what is suggested by mapbox-gl-js's [documentation](https://docs.mapbox.com/mapbox-gl-js/api/markers/#geolocatecontrol#trigger) or [initial github issue on the subject](https://github.com/mapbox/mapbox-gl-js/issues/5464) cannot be reproduced with vue-mapbox-gl

**Comment by titouanmathis** [comment]
Could you set up a reproduction project on stackblitz or any other tool? This would help me debug this.

**Comment by tmlmt** [comment]
There you go: https://stackblitz.com/edit/github-jbfwmb?file=README.md

**Comment by tmlmt** [comment]
Any news on this one @titouanmathis? Shall the issue be reopened?

**Comment by titouanmathis** [comment]
The problem comes from the `useControl` utility function which assigns the control instance before adding it to the map, see https://github.com/studiometa/vue-mapbox-gl/blob/develop/packages/vue-mapbox-gl/composables/useControl.js#L39-L43.

Based on my previous example, wrapping the `trigger()` call in a `setTimeout` (or `nextTick`) fixes the issue by delaying its execution to after adding the control to the map.

```js
<script setup>
  import { ref, watch, nextTick } from 'vue';
 
  const geolocate = ref();

  watch(geolocate, (geolocateControl) => {
    if (geolocateControl) {
      nextTick(() => geolocateControl.control.trigger());
    }
  });
</script>

<template>
  <mapbox-map>
    <mapbox-geolocate-control ref="geolocate" />
  </mapbox-map>
</template>
```

I will push a fix to change the behavior of the `useControl` function, so that any watch function on a control will be called after the control has been added to the map.

**Comment by tmlmt** [comment]
Have you tested your fix, @titouanmathis? The Stackblitz above, updated with v2.0.3, still says "Geolocate control triggered before added to a map". And for some reason on my browser (Firefox on Ubuntu), neither setTimeout nor nextTick work. The request for location control only triggers with the "onClick"

**Comment by titouanmathis** [comment]
I published a fix in 2.0.4 that should improve timings so the control would be exposed only after being added to the map. You might still encounter some warnings if geolocation is disabled in the browser as the permissions API is async (see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query#return_value)). 

The snippet I gave you was also not quite right, as we are watching the ref and not its `control` property. Since the control property is set lazily, the watcher on the ref will not be trigger when this property changes.

It works (in Firefox) when using a computed:

```js
const geolocate = ref();
const control = computed(() => geolocate.value?.control);

watch(control, (geolocateControl) => {
  if (geolocateControl) {
    geolocateControl.trigger();
  }
});
```

See https://stackblitz.com/edit/github-jbfwmb-b5jqlq?file=app.vue.

**Comment by tmlmt** [comment]
Hey @titouanmathis, coming back to this issue, as the same latest Stackblitz you give does not work on Chrome / Chromium, with still the same error: `Geolocate control triggered before added to a map`, while it indeed still works in Firefox. What could we do?

**Comment by titouanmathis** [comment]
Hey @tmlmt, sorry to hear that this is still an issue. I  am away for some days, I'll have a look at this when I get back.

**Comment by tmlmt** [comment]
Hey @titouanmathis, thanks a lot for setting this up.
I can confirm that on mobile (iOS), things work with Chrome, Firefox, Safari and Brave.
However, on laptop as I just tried, things don't work on Chrome nor on Firefox. I see `Can use the trigger() method` in the console, and the browser is asking me to confirm that I allow location sharing, but the location doesn't show on the map:
- On Chrome, I get the following error message: `Network location provider at 'https://www.9oo91eapis.qjz9zk/' : ERR_BLOCKED_BY_CLIENT.`
- On Firefox, I don't see any additional error. 
Could that be due to deploying this preview on Netlify?

**Comment by titouanmathis** [comment]
Thanks for the feedback!

> On Chrome, I get the following error message: Network location provider at 'https://www.9oo91eapis.qjz9zk/' : ERR_BLOCKED_BY_CLIENT.

This error might be due to an adblocker or a configuration in your browser, but the fact that the request happens tells us that the geolocation is correctly triggered. 

> On Firefox, I don't see any additional error. Could that be due to deploying this preview on Netlify?

I don't think so, the demo on Netlify is working fine with Firefox on my end. I would suspect an extension or a configuration of your browser, like in Chrome.

**Comment by tmlmt** [comment]
Hey @titouanmathis, sorry for not reverting sooner. 
- Chrome: I confirm that it works. The error message came from my test using `ungoogled-chromium`, a Chromium version stripped out of all google stuff. That error is thrown (with that dummy google-ish url) to signal a blocked connection attempt to Google servers. It looks like when the Geolocation feature of Mapbox is triggered, something is shared with Google (!). Good to know...
- Firefox: I confirm that it works on my end when retrying from a known wifi network. 

So we're good to go I think :) Thanks for your help with this one again.

**Comment by Remraf23** [comment]
Hey @titouanmathis, i've followed the examples above but unfortunately i'm still having trouble manually triggering the geolocate control. `geolocate.value.control` seems to always be undefined for me

![Image](https://github.com/user-attachments/assets/82c6c044-11dc-4880-823a-f6231a10bed6)

**Comment by titouanmathis** [comment]
Hey @Remraf23, could you please provide a link to a reproduction like mentioned above?

**Comment by Remraf23** [comment]
Here's a stackblitz with the original code as an example: https://stackblitz.com/edit/github-jbfwmb-39nkvy6w?file=app.vue

let me know if i've set this up wrong but the geolocation isn't triggering at all for me, i'm not getting the 'Can use the trigger() method.' console log either in the console

**Comment by titouanmathis** [comment]
Hey @Remraf23, I took some time to take a look. Unfortunately, the geolocate controller is added asynchronously without notice of when it is available for usage, so we can not have a reliable way to trigger geolocation on map load. This is a known issue of the mapbox-gl package and won't be fixed in this package as too unreliable.

**Comment by Remraf23** [comment]
Okie doke, thank you for taking a look anyway 🙏
